# Generated by Django 4.2.7 on 2025-10-30 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('account_type', models.CharField(choices=[('SINGLE', 'Single Account'), ('JOINT', 'Joint Account')], max_length=10)),
                ('person1_first_name', models.CharField(max_length=100)),
                ('person1_last_name', models.CharField(max_length=100)),
                ('person1_contact', models.CharField(max_length=20)),
                ('person1_address', models.TextField()),
                ('person1_area_code', models.CharField(max_length=10)),
                ('person1_next_of_kin', models.CharField(max_length=100)),
                ('person1_photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('person1_signature', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('person1_nin', models.CharField(max_length=20, unique=True)),
                ('person1_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('person2_first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('person2_last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('person2_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('person2_address', models.TextField(blank=True, null=True)),
                ('person2_area_code', models.CharField(blank=True, max_length=10, null=True)),
                ('person2_next_of_kin', models.CharField(blank=True, max_length=100, null=True)),
                ('person2_photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('person2_signature', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('person2_nin', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('person2_gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True)),
                ('business_location', models.CharField(max_length=100)),
                ('business_sector', models.CharField(max_length=100)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('loan_officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
