# Generated by Django 4.2.7 on 2025-11-21 12:57

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client_accounts', '0004_clientaccount_last_savings_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('EDIT_REQUEST', 'Edit Request Submitted'), ('APPROVE_EDIT', 'Edit Request Approved'), ('REJECT_EDIT', 'Edit Request Rejected'), ('SAVINGS_TX', 'Savings Transaction')], max_length=30)),
                ('changed_data', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ClientEditRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('data', models.JSONField(help_text="JSON object of proposed changes, e.g. {'person1_contact': '2567...','business_sector':'Retail'}")),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_comment', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('STAFF', 'Staff'), ('MANAGER', 'Manager'), ('ACCOUNTANT', 'Accountant'), ('LOAN_OFFICER', 'Loan Officer')], default='STAFF', max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='clientaccount',
            options={'ordering': ['-registration_date']},
        ),
        migrations.AlterModelOptions(
            name='savingstransaction',
            options={'ordering': ['-transaction_date']},
        ),
        migrations.AddField(
            model_name='clientaccount',
            name='is_edit_pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='clientaccount',
            name='account_number',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='clientaccount',
            name='loan_officer',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='client_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clientaccount',
            name='savings_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='savingstransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='savingstransaction',
            name='client_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_transactions', to='client_accounts.clientaccount'),
        ),
        migrations.AlterField(
            model_name='savingstransaction',
            name='processed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_savings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='clientaccount',
            index=models.Index(fields=['account_number'], name='client_acco_account_f238bb_idx'),
        ),
        migrations.AddIndex(
            model_name='clientaccount',
            index=models.Index(fields=['person1_nin'], name='client_acco_person1_69efce_idx'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clienteditrequest',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_requests', to='client_accounts.clientaccount'),
        ),
        migrations.AddField(
            model_name='clienteditrequest',
            name='requested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_edit_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clienteditrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_edit_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientauditlog',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='client_accounts.clientaccount'),
        ),
        migrations.AddField(
            model_name='clientauditlog',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
