# Generated by Django 4.2.7 on 2025-11-10 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('DAILY', 'Daily Report'), ('WEEKLY', 'Weekly Report'), ('MONTHLY', 'Monthly Report'), ('QUARTERLY', 'Quarterly Report'), ('YEARLY', 'Yearly Report')], max_length=20)),
                ('report_date', models.DateField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('total_accounts', models.IntegerField(default=0)),
                ('active_accounts', models.IntegerField(default=0)),
                ('total_savings', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_loans_disbursed', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_loans_pending', models.IntegerField(default=0)),
                ('total_loans_approved', models.IntegerField(default=0)),
                ('total_loans_rejected', models.IntegerField(default=0)),
                ('total_loans_completed', models.IntegerField(default=0)),
                ('total_loans_defaulted', models.IntegerField(default=0)),
                ('total_interest_earned', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('staff_loan_counts', models.JSONField(default=dict)),
                ('staff_savings_counts', models.JSONField(default=dict)),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
