# Generated by Django 4.2.7 on 2025-11-10 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemreport',
            name='total_loans_rejected',
        ),
        migrations.AddField(
            model_name='systemreport',
            name='chart_image',
            field=models.ImageField(blank=True, null=True, upload_to='reports/charts/'),
        ),
        migrations.AlterField(
            model_name='systemreport',
            name='generated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='systemreport',
            name='report_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='systemreport',
            name='report_type',
            field=models.CharField(choices=[('DAILY', 'Daily Report'), ('WEEKLY', 'Weekly Report'), ('MONTHLY', 'Monthly Report')], max_length=20),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
