# Generated by Django 4.2.7 on 2025-11-10 13:24

from django.db import migrations, models
import django.utils.timezone
import reports.models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_remove_systemreport_total_loans_rejected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemreport',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='reports/pdfs/'),
        ),
        migrations.AlterField(
            model_name='systemreport',
            name='chart_image',
            field=models.ImageField(blank=True, null=True, upload_to=reports.models.report_chart_path),
        ),
        migrations.AlterField(
            model_name='systemreport',
            name='report_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='systemreport',
            name='report_type',
            field=models.CharField(choices=[('DAILY', 'Daily Report'), ('WEEKLY', 'Weekly Report'), ('MONTHLY', 'Monthly Report'), ('YEARLY', 'Yearly Report')], max_length=20),
        ),
    ]
