# Generated by Django 4.2.7 on 2025-11-21 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_systemreport_pdf_file_alter_systemreport_chart_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemreport',
            options={'ordering': ['-report_date', '-generated_at'], 'verbose_name': 'System Report', 'verbose_name_plural': 'System Reports'},
        ),
        migrations.AddField(
            model_name='activitylog',
            name='extra_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemreport',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='systemreport',
            name='total_guarantors',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='systemreport',
            name='total_transactions',
            field=models.IntegerField(default=0),
        ),
    ]
