# Generated by Django 4.2.7 on 2025-10-31 06:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client_accounts', '0003_clientaccount_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guarantor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guarantor_type', models.CharField(choices=[('INTERNAL', 'Internal (Existing Customer)'), ('EXTERNAL', 'External')], max_length=20)),
                ('external_name', models.CharField(blank=True, max_length=100)),
                ('external_contact', models.CharField(blank=True, max_length=20)),
                ('external_nin', models.CharField(blank=True, max_length=20)),
                ('external_address', models.TextField(blank=True)),
                ('internal_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client_accounts.clientaccount')),
            ],
        ),
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('monthly_installment', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('collateral_description', models.TextField()),
                ('collateral_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('DISBURSED', 'Disbursed')], default='PENDING', max_length=20)),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('review_date', models.DateTimeField(blank=True, null=True)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_loans', to=settings.AUTH_USER_MODEL)),
                ('client_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_accounts.clientaccount')),
                ('guarantors', models.ManyToManyField(to='loans.guarantor')),
                ('loan_officer', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoanProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('loan_type', models.CharField(choices=[('PRIME_EXPRESS', 'Prime Express (1 Week)'), ('BUSINESS', 'Business Loan (1 Month)'), ('BI', 'BI Loan (2 Weeks)')], max_length=20)),
                ('interest_method', models.CharField(choices=[('FLAT', 'Flat Rate'), ('REDUCING', 'Reducing Balance'), ('COMPOUND', 'Compound Interest')], default='FLAT', max_length=20)),
                ('payment_mode', models.CharField(choices=[('WEEKLY', 'Weekly'), ('BI_WEEKLY', 'Bi-Weekly'), ('MONTHLY', 'Monthly')], max_length=20)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('loan_period', models.IntegerField(help_text='Period in days')),
                ('number_of_installments', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoanDisbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disbursement_date', models.DateTimeField()),
                ('disbursed_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_reference', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('disbursed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('loan_application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='loans.loanapplication')),
            ],
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='loan_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.loanproduct'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_loans', to=settings.AUTH_USER_MODEL),
        ),
    ]
