# Generated by Django 4.2.7 on 2025-10-31 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('transaction_reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='loandisbursement',
            name='disbursed_by',
        ),
        migrations.RemoveField(
            model_name='loandisbursement',
            name='loan_application',
        ),
        migrations.RenameField(
            model_name='loanapplication',
            old_name='review_date',
            new_name='disbursement_date',
        ),
        migrations.RenameField(
            model_name='loanapplication',
            old_name='monthly_installment',
            new_name='due_amount',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='guarantors',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='loanproduct',
            name='loan_period',
        ),
        migrations.RemoveField(
            model_name='loanproduct',
            name='number_of_installments',
        ),
        migrations.RemoveField(
            model_name='loanproduct',
            name='payment_mode',
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='collateral_images',
            field=models.ImageField(blank=True, null=True, upload_to='collateral_images/'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='loan_period',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='number_of_installments',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='payment_mode',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='collateral_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='collateral_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('DISBURSED', 'Disbursed'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('DEFAULTED', 'Defaulted')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='loanproduct',
            name='interest_method',
            field=models.CharField(choices=[('FLAT', 'Flat Rate'), ('REDUCING', 'Reducing Balance')], default='FLAT', max_length=20),
        ),
        migrations.AlterField(
            model_name='loanproduct',
            name='loan_type',
            field=models.CharField(choices=[('PRIME_EXPRESS', 'Prime Express (1 Week)'), ('BUSINESS', 'Business Loan (1 Month)'), ('BI', 'BI Loan (2 Weeks)')], max_length=20, unique=True),
        ),
        migrations.DeleteModel(
            name='Guarantor',
        ),
        migrations.DeleteModel(
            name='LoanDisbursement',
        ),
        migrations.AddField(
            model_name='loanpayment',
            name='loan_application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.loanapplication'),
        ),
        migrations.AddField(
            model_name='loanpayment',
            name='received_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
