# Generated by Django 4.2.7 on 2025-10-31 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_accounts', '0003_clientaccount_is_approved'),
        ('loans', '0002_loanpayment_remove_loandisbursement_disbursed_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='collateral_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='collateral_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('DISBURSED', 'Disbursed'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='Guarantor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guarantor_type', models.CharField(choices=[('INTERNAL', 'Internal (Existing Customer)'), ('EXTERNAL', 'External')], max_length=20)),
                ('external_name', models.CharField(blank=True, max_length=100)),
                ('external_contact', models.CharField(blank=True, max_length=20)),
                ('external_nin', models.CharField(blank=True, max_length=20)),
                ('external_address', models.TextField(blank=True)),
                ('internal_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client_accounts.clientaccount')),
            ],
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='guarantor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loans.guarantor'),
        ),
    ]
