# Generated by Django 4.2.7 on 2025-11-03 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_remove_loanapplication_due_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanapplication',
            name='approved_interest_rate',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='approved_loan_amount',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='approved_loan_period',
        ),
    ]
