# Generated by Django 4.2.7 on 2025-11-22 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0007_alter_guarantor_guarantor_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='interest_amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='payment_mode',
            field=models.CharField(default='', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
        ),
    ]
