# Generated by Django 4.2.7 on 2025-11-22 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0008_alter_loanapplication_interest_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanproduct',
            name='number_of_installments',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
